---
- name: Example Ansible playbook for ENV variables
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - custom-role

  environment:
    EXAMPLE: "Fubar"
    MY_VAR1: "Variable value1"

  tasks:
    # Environment variable at playbook level
    - name: Environment var at Playbook level
      ansible.builtin.command: "echo $EXAMPLE"

    # Environment variable only for tasks
    - name: Environment car only for task level
      environment: 
        MY_TASK_LEVEL_VARIABLE: "Hello World!"
      ansible.builtin.command: "echo $MY_TASK_LEVEL_VARIABLE"

    # Testing Environment value
    - name: Testing both playbook level as well as environment level variables
      ansible.builtin.command: "echo $EXAMPLE $MY_TASK_LEVEL_VARIABLE"
